/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: sanity/schemas/schema.json
export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type DividerSection = {
  _type: "dividerSection";
  style?: "tartan" | "solid" | "line";
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  height?: "sm" | "md" | "lg";
};

export type SubheadingSection = {
  _type: "subheadingSection";
  id?: string;
  text?: string;
};

export type ImageSection = {
  _type: "imageSection";
  title?: string;
  body?: BlockContentSection;
  image?: ResponsiveImage;
  layout?: "left" | "right";
  fullWidth?: boolean;
};

export type ContactSection = {
  _type: "contactSection";
  id?: string;
  title?: string;
  phone?: string;
  address?: string;
  email?: string;
  subtitle?: string;
  hours?: Array<{
    days?: string;
    time?: string;
    _key: string;
  }>;
};

export type FaqSection = {
  _type: "faqSection";
  id?: string;
  title?: string;
  subtitle?: string;
  items?: Array<{
    question?: string;
    answer?: string;
    _key: string;
  }>;
};

export type AboutSection = {
  _type: "aboutSection";
  id?: string;
  title?: string;
  description?: string;
  features?: Array<{
    icon?: string;
    title?: string;
    description?: string;
    _key: string;
  }>;
};

export type HeroSection = {
  _type: "heroSection";
  title?: string;
  supra?: string;
  description?: string;
  ctaLabel?: string;
  ctaHref?: string;
  backgroundImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  overlayOpacity?: number;
};

export type BlockContentSection = Array<
  | {
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "normal" | "h1" | "h2" | "h3" | "h4" | "blockquote";
      listItem?: "bullet";
      markDefs?: Array<{
        href?: string;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    }
  | {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: "image";
      _key: string;
    }
>;

export type ResponsiveImage = {
  _type: "responsiveImage";
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  aspectRatio?: "3/4" | "9/16" | "16/9" | "1/1" | "4/3" | "3/2";
};

export type TranslationMetadata = {
  _id: string;
  _type: "translation.metadata";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  translations?: InternationalizedArrayReference;
  schemaTypes?: Array<string>;
};

export type InternationalizedArrayReference = Array<
  {
    _key: string;
  } & InternationalizedArrayReferenceValue
>;

export type PageReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "page";
};

export type SettingsReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "settings";
};

export type InternationalizedArrayReferenceValue = {
  _type: "internationalizedArrayReferenceValue";
  value?: PageReference | SettingsReference;
};

export type Settings = {
  _id: string;
  _type: "settings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  language?: string;
  title?: string;
  url?: string;
  navigation?: {
    navigationLinks?: Array<{
      label?: string;
      href?: string;
      external?: boolean;
      order?: number;
      _key: string;
    }>;
  };
  phone?: string;
  mail?: string;
  address?: string;
  social?: Array<{
    media?: "Twitter" | "Facebook" | "Instagram" | "Linkedin" | "Youtube";
    url?: string;
    _key: string;
  }>;
  tagline?: string;
  openingHours?: Array<{
    days?: string;
    time?: string;
    _key: string;
  }>;
  footerNavLinks?: Array<{
    label?: string;
    href?: string;
    _key: string;
  }>;
  footerNavLegalLinks?: Array<{
    label?: string;
    href?: string;
    _key: string;
  }>;
  footerGalleryImages?: Array<
    {
      _key: string;
    } & ResponsiveImage
  >;
  description?: string;
  keywords?: Array<string>;
  openGraphImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type Page = {
  _id: string;
  _type: "page";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  language?: string;
  title?: string;
  slug?: Slug;
  metadata?: {
    metaTitle?: string;
    metaDescription?: string;
    keywords?: Array<string>;
    ogImage?: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: "image";
    };
    noIndex?: boolean;
  };
  sections?: Array<
    | ({
        _key: string;
      } & HeroSection)
    | ({
        _key: string;
      } & AboutSection)
    | ({
        _key: string;
      } & FaqSection)
    | ({
        _key: string;
      } & ContactSection)
    | ({
        _key: string;
      } & ImageSection)
    | ({
        _key: string;
      } & SubheadingSection)
    | ({
        _key: string;
      } & DividerSection)
  >;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | SanityImageAssetReference
  | DividerSection
  | SubheadingSection
  | ImageSection
  | ContactSection
  | FaqSection
  | AboutSection
  | HeroSection
  | BlockContentSection
  | ResponsiveImage
  | TranslationMetadata
  | InternationalizedArrayReference
  | PageReference
  | SettingsReference
  | InternationalizedArrayReferenceValue
  | Settings
  | SanityImageCrop
  | SanityImageHotspot
  | Page
  | Slug
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: sanity/schemas/pages/page.queries.ts
// Variable: pageQuery
// Query: *[_type == "page" && slug.current == $slug && (language == $language || !defined(language))][0]{  _id,  _type,  _createdAt,  _updatedAt,  _rev,  title,  slug,  metadata{    metaTitle,    metaDescription,    keywords,    ogImage{      ...,      asset->    },    noIndex  },  sections[]{    _key,    _type,    ...,    // Hero section - background image with metadata    backgroundImage{      ...,      asset->{ _id, url, metadata { lqip, dimensions } }    },    // About section - features    features[]{      ...,    },    // FAQ section - items    items[]{      ...,    },    // Image section - responsive image with metadata    image{      ...,      image{        ...,        asset->{ _id, url, metadata { lqip, dimensions } }      },      aspectRatio    },    // Rich text body    body[]{      ...,      _type == 'image' => {        ...,        asset->{ _id, url, metadata { lqip, dimensions } }      }    },    // Divider section - optional pattern/texture image    _type == 'dividerSection' => {      image{        ...,        asset->{ _id, url, metadata { lqip, dimensions } }      }    },  }}
export type PageQueryResult = {
  _id: string;
  _type: "page";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string | null;
  slug: Slug | null;
  metadata: {
    metaTitle: string | null;
    metaDescription: string | null;
    keywords: Array<string> | null;
    ogImage: {
      asset: {
        _id: string;
        _type: "sanity.imageAsset";
        _createdAt: string;
        _updatedAt: string;
        _rev: string;
        originalFilename?: string;
        label?: string;
        title?: string;
        description?: string;
        altText?: string;
        sha1hash?: string;
        extension?: string;
        mimeType?: string;
        size?: number;
        assetId?: string;
        uploadId?: string;
        path?: string;
        url?: string;
        metadata?: SanityImageMetadata;
        source?: SanityAssetSourceData;
      } | null;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: "image";
    } | null;
    noIndex: boolean | null;
  } | null;
  sections: Array<
    | {
        _key: string;
        _type: "aboutSection";
        id?: string;
        title?: string;
        description?: string;
        features: Array<{
          icon?: string;
          title?: string;
          description?: string;
          _key: string;
        }> | null;
        backgroundImage: null;
        items: null;
        image: null;
        body: null;
      }
    | {
        _key: string;
        _type: "contactSection";
        id?: string;
        title?: string;
        phone?: string;
        address?: string;
        email?: string;
        subtitle?: string;
        hours?: Array<{
          days?: string;
          time?: string;
          _key: string;
        }>;
        backgroundImage: null;
        features: null;
        items: null;
        image: null;
        body: null;
      }
    | {
        _key: string;
        _type: "dividerSection";
        style?: "line" | "solid" | "tartan";
        image: {
          asset: {
            _id: string;
            url: string | null;
            metadata: {
              lqip: string | null;
              dimensions: SanityImageDimensions | null;
            } | null;
          } | null;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          _type: "image";
        } | null;
        height?: "lg" | "md" | "sm";
        backgroundImage: null;
        features: null;
        items: null;
        body: null;
      }
    | {
        _key: string;
        _type: "faqSection";
        id?: string;
        title?: string;
        subtitle?: string;
        items: Array<{
          question?: string;
          answer?: string;
          _key: string;
        }> | null;
        backgroundImage: null;
        features: null;
        image: null;
        body: null;
      }
    | {
        _key: string;
        _type: "heroSection";
        title?: string;
        supra?: string;
        description?: string;
        ctaLabel?: string;
        ctaHref?: string;
        backgroundImage: {
          asset: {
            _id: string;
            url: string | null;
            metadata: {
              lqip: string | null;
              dimensions: SanityImageDimensions | null;
            } | null;
          } | null;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          alt?: string;
          _type: "image";
        } | null;
        overlayOpacity?: number;
        features: null;
        items: null;
        image: null;
        body: null;
      }
    | {
        _key: string;
        _type: "imageSection";
        title?: string;
        body: Array<
          | {
              children?: Array<{
                marks?: Array<string>;
                text?: string;
                _type: "span";
                _key: string;
              }>;
              style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "normal";
              listItem?: "bullet";
              markDefs?: Array<{
                href?: string;
                _type: "link";
                _key: string;
              }>;
              level?: number;
              _type: "block";
              _key: string;
            }
          | {
              asset: {
                _id: string;
                url: string | null;
                metadata: {
                  lqip: string | null;
                  dimensions: SanityImageDimensions | null;
                } | null;
              } | null;
              media?: unknown;
              hotspot?: SanityImageHotspot;
              crop?: SanityImageCrop;
              alt?: string;
              _type: "image";
              _key: string;
            }
        > | null;
        image: {
          _type: "responsiveImage";
          image: {
            asset: {
              _id: string;
              url: string | null;
              metadata: {
                lqip: string | null;
                dimensions: SanityImageDimensions | null;
              } | null;
            } | null;
            media?: unknown;
            hotspot?: SanityImageHotspot;
            crop?: SanityImageCrop;
            alt?: string;
            _type: "image";
          } | null;
          aspectRatio: "1/1" | "16/9" | "3/2" | "3/4" | "4/3" | "9/16" | null;
        } | null;
        layout?: "left" | "right";
        fullWidth?: boolean;
        backgroundImage: null;
        features: null;
        items: null;
      }
    | {
        _key: string;
        _type: "subheadingSection";
        id?: string;
        text?: string;
        backgroundImage: null;
        features: null;
        items: null;
        image: null;
        body: null;
      }
  > | null;
} | null;

// Source: sanity/schemas/pages/page.queries.ts
// Variable: allPagesQuery
// Query: *[_type == "page" && (language == $language || !defined(language))]{  _id,  title,  slug}
export type AllPagesQueryResult = Array<{
  _id: string;
  title: string | null;
  slug: Slug | null;
}>;

// Source: sanity/schemas/settings.queries.ts
// Variable: navigationQuery
// Query: *[_type == "settings" && (language == $language || !defined(language))][0]{  _id,  navigation{    navigationLinks[]{      label,      href,      external,      order    } | order(order asc)  }}
export type NavigationQueryResult = {
  _id: string;
  navigation: {
    navigationLinks: Array<{
      label: string | null;
      href: string | null;
      external: boolean | null;
      order: number | null;
    }> | null;
  } | null;
} | null;

// Source: sanity/schemas/settings.queries.ts
// Variable: settingsQuery
// Query: *[_type == "settings" && (language == $language || !defined(language))][0] {    _id,    title,    description,    keywords,    url,    phone,    address,    mail,    social,    tagline,    openingHours[]{      _key,      days,      time    },    footerNavLinks[]{      _key,      label,      href    },    footerNavLegalLinks[]{      _key,      label,      href    },    footerGalleryImages[]{      _key,      image{        ...,        asset->{ _id, url, metadata{ lqip, dimensions } }      },      aspectRatio    }  }
export type SettingsQueryResult = {
  _id: string;
  title: string | null;
  description: string | null;
  keywords: Array<string> | null;
  url: string | null;
  phone: string | null;
  address: string | null;
  mail: string | null;
  social: Array<{
    media?: "Facebook" | "Instagram" | "Linkedin" | "Twitter" | "Youtube";
    url?: string;
    _key: string;
  }> | null;
  tagline: string | null;
  openingHours: Array<{
    _key: string;
    days: string | null;
    time: string | null;
  }> | null;
  footerNavLinks: Array<{
    _key: string;
    label: string | null;
    href: string | null;
  }> | null;
  footerNavLegalLinks: Array<{
    _key: string;
    label: string | null;
    href: string | null;
  }> | null;
  footerGalleryImages: Array<{
    _key: string;
    image: {
      asset: {
        _id: string;
        url: string | null;
        metadata: {
          lqip: string | null;
          dimensions: SanityImageDimensions | null;
        } | null;
      } | null;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: "image";
    } | null;
    aspectRatio: "1/1" | "16/9" | "3/2" | "3/4" | "4/3" | "9/16" | null;
  }> | null;
} | null;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    "*[_type == \"page\" && slug.current == $slug && (language == $language || !defined(language))][0]{\n  _id,\n  _type,\n  _createdAt,\n  _updatedAt,\n  _rev,\n  title,\n  slug,\n  metadata{\n    metaTitle,\n    metaDescription,\n    keywords,\n    ogImage{\n      ...,\n      asset->\n    },\n    noIndex\n  },\n  sections[]{\n    _key,\n    _type,\n    ...,\n    // Hero section - background image with metadata\n    backgroundImage{\n      ...,\n      asset->{ _id, url, metadata { lqip, dimensions } }\n    },\n    // About section - features\n    features[]{\n      ...,\n    },\n    // FAQ section - items\n    items[]{\n      ...,\n    },\n    // Image section - responsive image with metadata\n    image{\n      ...,\n      image{\n        ...,\n        asset->{ _id, url, metadata { lqip, dimensions } }\n      },\n      aspectRatio\n    },\n    // Rich text body\n    body[]{\n      ...,\n      _type == 'image' => {\n        ...,\n        asset->{ _id, url, metadata { lqip, dimensions } }\n      }\n    },\n    // Divider section - optional pattern/texture image\n    _type == 'dividerSection' => {\n      image{\n        ...,\n        asset->{ _id, url, metadata { lqip, dimensions } }\n      }\n    },\n  }\n}": PageQueryResult;
    '*[_type == "page" && (language == $language || !defined(language))]{\n  _id,\n  title,\n  slug\n}': AllPagesQueryResult;
    '*[_type == "settings" && (language == $language || !defined(language))][0]{\n  _id,\n  navigation{\n    navigationLinks[]{\n      label,\n      href,\n      external,\n      order\n    } | order(order asc)\n  }\n}': NavigationQueryResult;
    '\n  *[_type == "settings" && (language == $language || !defined(language))][0] {\n    _id,\n    title,\n    description,\n    keywords,\n    url,\n    phone,\n    address,\n    mail,\n    social,\n    tagline,\n    openingHours[]{\n      _key,\n      days,\n      time\n    },\n    footerNavLinks[]{\n      _key,\n      label,\n      href\n    },\n    footerNavLegalLinks[]{\n      _key,\n      label,\n      href\n    },\n    footerGalleryImages[]{\n      _key,\n      image{\n        ...,\n        asset->{ _id, url, metadata{ lqip, dimensions } }\n      },\n      aspectRatio\n    }\n  }\n': SettingsQueryResult;
  }
}
